"""add project metadata fields

Revision ID: 08170c620fae
Revises: ff8d14b5d2fb
Create Date: 2024-04-23 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '08170c620fae'
down_revision = 'ff8d14b5d2fb'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phases', sa.JSON(), nullable=True, server_default='{"frontend": 0, "backend": 0, "integration": 0}'))
        batch_op.add_column(sa.Column('personas', sa.JSON(), nullable=True, server_default='[]'))
        batch_op.add_column(sa.Column('assets', sa.JSON(), nullable=True, server_default='[]'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('assets')
        batch_op.drop_column('personas')
        batch_op.drop_column('phases')
        batch_op.drop_column('status')
        batch_op.drop_column('type')
    # ### end Alembic commands ### 